package dev.symbiosis.panel
// Generated by AGP at build time from the git-derived version. Stubbed here so
// the fast kotlinc type-check - which runs without the Android SDK or Gradle -
// still resolves MainActivity.SHELL_VERSION.
object BuildConfig { const val PANEL_VERSION = "0.dev" }
